name: hello workflow

on:
  push:
    branches:
      -main

jobs:
  hello:
     runs-on: ubuntu-latest

     steps:
       - name: run hello 
         run: echo "hey you"

       - name: custom run
         run: |
           echo "This is custom script"
           mkdir -p myfolder
           echo "Script executed sucessfully"
  