name: hello workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
     runs-on: ubuntu-latest

     steps:
       - name: run hello 
         run: echo "hey you"

       - name: custom run
         run: |
<<<<<<< HEAD
          echo "This is custom script"
          mkdir -p myfolder
          echo "Script executed sucessfully"
          echo "done script"
  
=======
           echo "This is custom script"
           mkdir -p myfolder
           echo "Script executed sucessfully"
           echo"done script"
  
>>>>>>> 3ec6cf223d5f375d8b26b0060456a7cc969fa363
